import { createPrivateKey, createPublicKey, sign, timingSafeEqual, verify } from "node:crypto";
import { types } from "node:util";

import { canonicalBytes, digestHex } from "../../core/canonical.mjs";
import { AGENT_HANDSHAKE_V2_PROTOCOL } from "./constants.mjs";
import { rawEd25519PublicKey } from "./host-key-certificate.mjs";
import { validateAgentHandshakeV2Party } from "./party.mjs";
import { validateIdentityPolicy } from "./terms.mjs";

export const AGENT_HANDSHAKE_V2_DESCRIPTOR_SCHEMA = "clockchain.agent-handshake-descriptor/v2";
const DESCRIPTOR_KEYS=Object.freeze(["agreementExpiresAtMs","externalBusinessActionPerformed","hostSessionKeyCertificateDigest","identityPolicy","initiator","operatorPublicKey","protocol","reference","repositorySha","responder","schema","sessionId","sessionOpenedAtMs","sessionOpenedBlock","statementDigest"]);
const OPERATOR_KEYS=Object.freeze(["algorithm","keyId","publicKey","signature"]);
const ENVELOPE_KEYS=Object.freeze(["descriptor","operator"]);
const DIGEST=/^[0-9a-f]{64}$/;const DECIMAL=/^(?:0|[1-9][0-9]*)$/;const SHA=/^[0-9a-f]{40}$/;const UUID=/^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;const KID=/^[a-z0-9][a-z0-9-]{0,63}$/;const BASE64=/^[A-Za-z0-9+/]+={0,2}$/;
export class AgentHandshakeV2DescriptorError extends Error{constructor(){super("Agent handshake v2 descriptor verification failed.");this.name="AgentHandshakeV2DescriptorError";this.category="verification";this.code="AGENT_HANDSHAKE_V2_DESCRIPTOR_INVALID";}}
function invalid(){throw new AgentHandshakeV2DescriptorError();}
function exact(value,keys){try{if(value===null||typeof value!=="object"||Array.isArray(value)||types.isProxy(value)||![Object.prototype,null].includes(Object.getPrototypeOf(value)))invalid();const actual=Reflect.ownKeys(value);if(actual.length!==keys.length||actual.some((key)=>typeof key!=="string"||!keys.includes(key)))invalid();const result={};for(const key of keys){const property=Object.getOwnPropertyDescriptor(value,key);if(property?.enumerable!==true||!Object.hasOwn(property,"value"))invalid();result[key]=property.value;}return result;}catch(error){if(error instanceof AgentHandshakeV2DescriptorError)throw error;invalid();}}
function sameText(left,right){const a=Buffer.from(left,"utf8"),b=Buffer.from(right,"utf8");return a.length===b.length&&timingSafeEqual(a,b);}
function keyFromRaw(value){const prefix=Buffer.from("302a300506032b6570032100","hex");return createPublicKey({key:Buffer.concat([prefix,Buffer.from(value,"base64")]),format:"der",type:"spki"});}
function descriptor(value){const item=exact(value,DESCRIPTOR_KEYS);let policy,initiator,responder;try{policy=validateIdentityPolicy(item.identityPolicy);initiator=validateAgentHandshakeV2Party(item.initiator,{identityPolicy:policy});responder=validateAgentHandshakeV2Party(item.responder,{identityPolicy:policy});rawEd25519PublicKey(keyFromRaw(item.operatorPublicKey));}catch{invalid();}if(item.schema!==AGENT_HANDSHAKE_V2_DESCRIPTOR_SCHEMA||item.protocol!==AGENT_HANDSHAKE_V2_PROTOCOL||!UUID.test(item.sessionId)||!SHA.test(item.repositorySha)||typeof item.reference!=="string"||item.reference.length===0||!DIGEST.test(item.statementDigest)||!DIGEST.test(item.hostSessionKeyCertificateDigest)||!DECIMAL.test(item.sessionOpenedAtMs)||!DECIMAL.test(item.sessionOpenedBlock)||!DECIMAL.test(item.agreementExpiresAtMs)||BigInt(item.agreementExpiresAtMs)<=BigInt(item.sessionOpenedAtMs)||item.externalBusinessActionPerformed!==false||initiator.sessionKeyAddress===responder.sessionKeyAddress)invalid();return Object.freeze({...item,identityPolicy:policy,initiator,responder});}
function operator(value){const item=exact(value,OPERATOR_KEYS);if(item.algorithm!=="ed25519"||!KID.test(item.keyId)||typeof item.publicKey!=="string"||Buffer.from(item.publicKey,"base64").length!==32||typeof item.signature!=="string"||!BASE64.test(item.signature)||Buffer.from(item.signature,"base64").length!==64)invalid();return Object.freeze(item);}
function envelope(value){const item=exact(value,ENVELOPE_KEYS);return Object.freeze({descriptor:descriptor(item.descriptor),operator:operator(item.operator)});}
export function agentHandshakeV2DescriptorDigest(value){return digestHex(descriptor(value));}
export function createAgentHandshakeV2DescriptorEnvelope(value,{keyId,privateKeyPem}){const verified=descriptor(value);if(!KID.test(keyId))invalid();let privateKey;try{privateKey=createPrivateKey(privateKeyPem);}catch{invalid();}if(privateKey.asymmetricKeyType!=="ed25519"||!sameText(rawEd25519PublicKey(createPublicKey(privateKey)),verified.operatorPublicKey))invalid();return envelope({descriptor:verified,operator:{algorithm:"ed25519",keyId,publicKey:verified.operatorPublicKey,signature:sign(null,canonicalBytes(verified),privateKey).toString("base64")}});}
export function verifyAgentHandshakeV2DescriptorEnvelope(value,{expectedPublicKey,expectedHostSessionKeyCertificateDigest}){const verified=envelope(value);if(!sameText(verified.descriptor.operatorPublicKey,expectedPublicKey)||!sameText(verified.operator.publicKey,expectedPublicKey)||verified.descriptor.hostSessionKeyCertificateDigest!==expectedHostSessionKeyCertificateDigest)invalid();let accepted=false;try{accepted=verify(null,canonicalBytes(verified.descriptor),keyFromRaw(verified.operator.publicKey),Buffer.from(verified.operator.signature,"base64"));}catch{accepted=false;}if(!accepted)invalid();return verified;}
