import { recoverMessageAddress } from "viem";
import { types } from "node:util";

import { canonicalBytes } from "../../core/canonical.mjs";
import { AGENT_HANDSHAKE_V2_ROLES } from "./constants.mjs";
import { validateAgentHandshakeV2Party } from "./party.mjs";
import { validateIdentityPolicy } from "./terms.mjs";

export const AGENT_HANDSHAKE_V2_PARTY_RESULT_SCHEMA="clockchain.agent-handshake-party-result/v2";
export const AGENT_HANDSHAKE_V2_EVIDENCE_SCHEMA="clockchain.agent-handshake-evidence/v2";
const RESULT_KEYS=Object.freeze(["externalBusinessActionPerformed","party","policyDigest","reference","repositorySha","role","schema","sessionDigest","statementDigest","transitionDigests"]);
const ENVELOPE_KEYS=Object.freeze(["result","schema","signature"]);const SIGNATURE_KEYS=Object.freeze(["address","algorithm","value"]);
const DIGEST=/^[0-9a-f]{64}$/;const SHA=/^[0-9a-f]{40}$/;const EIP191=/^0x[0-9a-f]{130}$/;
export class AgentHandshakeV2EvidenceError extends Error{constructor(){super("Agent handshake v2 evidence verification failed.");this.name="AgentHandshakeV2EvidenceError";this.category="verification";this.code="AGENT_HANDSHAKE_V2_EVIDENCE_INVALID";}}
function invalid(){throw new AgentHandshakeV2EvidenceError();}
function exact(value,keys){try{if(value===null||typeof value!=="object"||Array.isArray(value)||types.isProxy(value)||![Object.prototype,null].includes(Object.getPrototypeOf(value)))invalid();const actual=Reflect.ownKeys(value);if(actual.length!==keys.length||actual.some((key)=>typeof key!=="string"||!keys.includes(key)))invalid();const result={};for(const key of keys){const property=Object.getOwnPropertyDescriptor(value,key);if(property?.enumerable!==true||!Object.hasOwn(property,"value"))invalid();result[key]=property.value;}return result;}catch(error){if(error instanceof AgentHandshakeV2EvidenceError)throw error;invalid();}}
function digestArray(value){if(!Array.isArray(value)||value.length!==3||value.some((entry)=>typeof entry!=="string"||!DIGEST.test(entry)))invalid();return Object.freeze([...value]);}
function result(value,identityPolicy){const item=exact(value,RESULT_KEYS);let party;try{party=validateAgentHandshakeV2Party(item.party,{identityPolicy});}catch{invalid();}if(item.schema!==AGENT_HANDSHAKE_V2_PARTY_RESULT_SCHEMA||item.externalBusinessActionPerformed!==false||!AGENT_HANDSHAKE_V2_ROLES.includes(item.role)||typeof item.reference!=="string"||item.reference.length===0||!SHA.test(item.repositorySha)||!DIGEST.test(item.policyDigest)||item.policyDigest!==party.policyDigest||!DIGEST.test(item.sessionDigest)||!DIGEST.test(item.statementDigest))invalid();return Object.freeze({...item,party,transitionDigests:digestArray(item.transitionDigests)});}
function signature(value){const item=exact(value,SIGNATURE_KEYS);if(!/^0x[0-9a-f]{40}$/.test(item.address)||item.algorithm!=="eip191"||!EIP191.test(item.value))invalid();return Object.freeze(item);}
function envelope(value,identityPolicy){const item=exact(value,ENVELOPE_KEYS);if(item.schema!==AGENT_HANDSHAKE_V2_EVIDENCE_SCHEMA)invalid();return Object.freeze({result:result(item.result,identityPolicy),schema:item.schema,signature:signature(item.signature)});}
export async function signAgentHandshakeV2Evidence({result:value,signMessage}){const inferred=value?.party?.erc8004===null?{erc8004:"not_required",chainId:null,registryAddress:null}:{erc8004:"required_existing_or_fresh",chainId:value?.party?.erc8004?.chainId,registryAddress:value?.party?.erc8004?.registryAddress};const verified=result(value,validateIdentityPolicy(inferred));if(typeof signMessage!=="function")invalid();let valueSignature;try{valueSignature=await signMessage(canonicalBytes(verified));}catch{invalid();}return envelope({result:verified,schema:AGENT_HANDSHAKE_V2_EVIDENCE_SCHEMA,signature:{address:verified.party.sessionKeyAddress,algorithm:"eip191",value:valueSignature}},inferred);}
export async function verifyAgentHandshakeV2Evidence({envelope:value,expectedParty,expectedPolicyDigest,expectedReference,expectedRepositorySha,expectedRole,expectedSessionDigest,expectedStatementDigest,expectedTransitionDigests,identityPolicy:rawPolicy}){let policy;try{policy=validateIdentityPolicy(rawPolicy);}catch{invalid();}const verified=envelope(value,policy);let party;try{party=validateAgentHandshakeV2Party(expectedParty,{identityPolicy:policy});}catch{invalid();}if(verified.result.role!==expectedRole||verified.result.reference!==expectedReference||verified.result.repositorySha!==expectedRepositorySha||verified.result.policyDigest!==expectedPolicyDigest||verified.result.sessionDigest!==expectedSessionDigest||verified.result.statementDigest!==expectedStatementDigest||!canonicalBytes(verified.result.party).equals(canonicalBytes(party))||!canonicalBytes({transitionDigests:verified.result.transitionDigests}).equals(canonicalBytes({transitionDigests:digestArray(expectedTransitionDigests)}))||verified.signature.address!==party.sessionKeyAddress)invalid();let recovered;try{recovered=(await recoverMessageAddress({message:{raw:canonicalBytes(verified.result)},signature:verified.signature.value})).toLowerCase();}catch{invalid();}if(recovered!==party.sessionKeyAddress)invalid();return verified;}
